import type { Metadata } from "next";
import { Fredoka, Nunito } from "next/font/google";

import MainWarper from "@/components/MainWarper";
import Toast from "@/components/Toast";

import "./tailwind.css";
import "./globals.scss";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const fredoka = Fredoka({
  variable: "--font-fredoka",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${nunito.variable} ${fredoka.variable} antialiased`}
      >
        <MainWarper>
          <Toast />
          {children}
        </MainWarper>
      </body>
    </html>
  );
}
